add new fixed param for collision safety margin
agimus-project/panda_torque_mpc pull request #17
Opened 2024-07-01 13:27 UTC by MedericFourmy

2024-07-01 13:40 UTC, Kotochleb requested changes

2024-07-01 13:40 UTC, Kotochleb commented on src/crocoddyl_reaching.cpp
> +        ub_col << std::numeric_limits<double>::infinity();
```suggestion
        Eigen::VectorXd col_lower_bound(1);
        Eigen::VectorXd col_upper_bound(1);
        col_lower_bound << config.collision_safety_margin;
        col_upper_bound << std::numeric_limits<double>::infinity();
```
Personally, I like this combination more. `lb` and `up` are a bit ambiguous IMO

2024-07-01 13:40 UTC, Kotochleb commented on config/controller_configs.yaml
> +    collision_safety_margin: 0.20  # in meter
```suggestion
    collision_safety_margin: 0.05  # in meter 
```
This change should not change behaviour of the system as a whole

2024-07-01 13:40 UTC, Kotochleb commented on src/crocoddyl_reaching.cpp
> +                ub_col
```suggestion
                col_lower_bound,
                col_upper_bound
```

2024-07-01 13:57 UTC, MedericFourmy commented on config/controller_configs.yaml
> +    collision_safety_margin: 0.20  # in meter
will fix

2024-07-01 15:55 UTC, Kotochleb requested changes

2024-07-01 15:55 UTC, Kotochleb commented on config/pose_publisher_params.yaml
Unrelated changes

2024-07-08 09:28 UTC, MaximilienNaveau commented
LGTM

2024-07-08 13:22 UTC, Kotochleb approved these changes
Looks good and I after testing I can confirm it works

2024-07-08 13:22 UTC, merged